### ISSUE TITLE
updatetracker command

### ISSUE THREAD

**Issue by epicpants** [epicpants/P2P#2]
<b>updatetracker:</b> message from peer to the tracker server
<updatetracker filename start_bytes end_bytes ip-address port-number>\n
updatetracker: message from tracker server to the peer program
if tracker file does not exist: <updatetracker filename ferr>\n
if tracker file update successful: <updatetracker filename succ>\n
any other error / unable to update tracker file: <updatetracker filename fail>\n

**Comment by cervz2** [comment]
Why

-Chris
