### ISSUE TITLE
LIST command

### ISSUE THREAD

**Issue by epicpants** [epicpants/P2P#3]
<b>LIST</b> – This command is sent by a connected peer to the tracker server to send over to
the requesting peer the list of (tracker) files in the shared directory at the server. The
format of the incoming message from the connected peer will be
<REQ LIST>\n
In reply to the LIST request the server reply message structure must be:
<REP LIST X>\n
<1 file1name file1size file1MD5>\n
<2 file2name file2size file2MD5>\n
...
<x fileXname fileXsize fileXMD5>\n
<REP LIST END>\n

**Comment by epicpants** [comment]
On the server end, I currently have each <..............> as a separate response as opposed to one long response. Each response is a char[1024] buffer which is null terminated. Note that the first response (<REP LIST X>) will tell the client how many responses are coming with the filenames/sizes/md5s. Then a final response will come as <REP LIST END>. I can include the angled brackets in the response if desired - let me know

**Comment by cervz2** [comment]
Does Lance have a github setup yet?

-Chris

**Comment by epicpants** [comment]
Not yet.

 Also wanted to say, if an error occurs in parsing one of the tracker files, the response will be <Error>
