### ISSUE TITLE
Removing dead peers from tracker files

### ISSUE THREAD

**Issue by epicpants** [epicpants/P2P#6]
When the server gets an updatetracker command, one of the housekeeping things it is supposed to do is remove dead peers from the tracker file. A peer is dead if its update time interval has elapsed. Does the tracker file API have this kind of check (or a way of removing dead peers)?

**Comment by abertels** [comment]
Any time update is called on a TrackerFile (with or without a command), each hosts with a timestamp that is older than 15 minutes is removed and the file is rewritten.
